import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "~/utils/api";
import { useToast } from "~/components/hooks/ui/use-toast";
import Posts from "~/components/app/Posts";
import { CardWithLink } from "~/components/app/HomeCard";
import LatestCommunities from "~/components/app/LatestCommunties";
import TopCommunities from "~/components/app/TopCommunities";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Kampusesor</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-row items-start justify-center gap-12">
        <div className="flex min-h-[calc(100vh-48px)] w-7/12 flex-col items-center justify-start overflow-hidden py-2">
          <Posts />
        </div>
        <div className="flex w-5/12 flex-col items-start justify-start gap-12">
          <CardWithLink />
          <LatestCommunities />
          <TopCommunities />
        </div>
      </div>
    </>
  );
};

export default Home;

 