import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "~/utils/api";
import { useToast } from "~/components/hooks/ui/use-toast";
import Posts from "~/components/app/Posts";
import { CardWithLink } from "~/components/app/HomeCard";
import LatestCommunities from "~/components/app/LatestCommunties";
import TopCommunities from "~/components/app/TopCommunities";
import { useEffect, useState } from "react";

const Home: NextPage = () => {
  const useWidth = () => {
    const [width, setWidth] = useState(0);
    const handleResize = () => setWidth(window.innerWidth);
    useEffect(() => {
      handleResize();
      window.addEventListener("resize", handleResize);
      return () => window.removeEventListener("resize", handleResize);
      // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);
    return width;
  };

  const width = useWidth();
  console.log(width);
  return (
    <>
      <Head>
        <title>Kampusesor</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col items-start justify-center gap-12 sm:flex-col md:flex-row">
        <div className="flex min-h-[calc(100vh-48px)] flex-col items-center justify-start overflow-hidden py-2 sm:w-full md:w-7/12">
          <Posts />
        </div>

        <div className="flex w-5/12 flex-col items-start justify-start gap-12">
          {width > 768 && (
            <>
              <CardWithLink />
              <LatestCommunities />
              <TopCommunities />
            </>
          )}
        </div>
      </div>
    </>
  );
};

export default Home;
